CELL_NUMBER_X = 13
CELL_NUMBER_Y = 9
GAME_VIEW_SIZE = (70 * CELL_NUMBER_X, 70 * CELL_NUMBER_Y)
BOTTOM_BAR_SIZE = 70
WINDOW_SIZE = (GAME_VIEW_SIZE[0], GAME_VIEW_SIZE[1]+BOTTOM_BAR_SIZE)
CELL_SIZE = (int(GAME_VIEW_SIZE[0] / CELL_NUMBER_X), int(GAME_VIEW_SIZE[1] / CELL_NUMBER_Y))
